using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ContentGenerator : MonoBehaviour
{
    //instance callable from anywhere
    public static ContentGenerator Instance { set; get; }

    //List of all the animals that have been generated by the algorithm
    private List<int> GeneratedAnimalsIDs = new List<int>();

    //List of all Resource stops currently in the players area
    private List<Vector2> ResourceStopLocations = new List<Vector2>();

    //Basically the size of the grids to generate, less equals a greater area.
    public static int DecimalPlacesToRound = 3;

    //current in to look at for the pocketpal
    public int currentIndex = 0;

    //random seeds
    private int currentSeed =0;
    private int newSeed = 0;

    void Start()
    {
        Instance = this;
    }

    private static int GetSeed(string seed, double lat, double lon)
    {
        String timeSeed = "";
        DateTime dt = DateTime.UtcNow;
        int minute = dt.Minute;
        minute -= minute % 10;

        timeSeed += dt.Date.DayOfYear.ToString() + dt.Hour.ToString() + minute.ToString();

        double roundedLat = System.Math.Round(lat, DecimalPlacesToRound);
        double roundedLon = System.Math.Round(lon, DecimalPlacesToRound);

        Debug.Log("Lat: " + roundedLat);
        Debug.Log("Lon:" + roundedLon);

        seed += roundedLat.ToString() + roundedLon.ToString() + timeSeed;

        return seed.GetHashCode();
    }

    private int GetID()
    {
        if (currentIndex >= GeneratedAnimalsIDs.Count)
        {
            currentIndex = 0;
        }
        int i = GeneratedAnimalsIDs[currentIndex];
        currentIndex++;
        return i;
    }

    public int GetSeededAnimal(string seed, double lat, double lon, int numberOfAnimals, List<float>samples)
    {
        newSeed = GetSeed(seed, lat, lon);
        if (newSeed != currentSeed)
        {
            currentSeed = newSeed;

            System.Random r = new System.Random(currentSeed);

            for (int i = 0; i < numberOfAnimals; i++)
            {
                GeneratedAnimalsIDs.Add(PocketPalSpawnManager.Sampler(r, samples));
            }
            return GetID();     
        }
        else
        {
            return GetID();
        }
    }

}
