using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ContentGenerator : MonoBehaviour
{
    //List of all the animals that have been generated by the algorithm
    private List<PocketPalData> GeneratedAnimals = new List<PocketPalData>();

    //List of all Resource stops currently in the players area
    private List<Vector2> ResourceStopLocations = new List<Vector2>();

    //Basically the size of the grids to generate, less equals a greater area.
    public int DecimalPlacesToRound = 4;

    void Start()
    {
        GenerateAnimalList("doombar", 50.12345, 50.12345);
    }

    //return the animal generated first
    public PocketPalData GetAnimal()
    {
        //Check to see if the list is empty. Could generate more here? 
        if (GeneratedAnimals.Count < 1) return null;

        PocketPalData ppd = GeneratedAnimals[0];
        GeneratedAnimals.Remove(ppd);
        return ppd;
    }

    private System.Random GetRandomFromSeed(string seed, double lat, double lon)
    {
        String timeSeed = "";
        DateTime dt = DateTime.UtcNow;
        int minute = dt.Minute;
        minute -= minute % 10;

        timeSeed += dt.Date.DayOfYear.ToString() + dt.Hour.ToString() + minute.ToString();

        Debug.Log(timeSeed);

        double roundedLat = System.Math.Round(lat, DecimalPlacesToRound);
        double roundedLon = System.Math.Round(lon, DecimalPlacesToRound);
        
        seed += lat.ToString() + lon.ToString() + timeSeed;
        Debug.Log(seed.GetHashCode());

        return new System.Random(seed.GetHashCode());
    }

    public void GenerateAnimalList(string seed, double lat, double lon)
    { 
        System.Random r = GetRandomFromSeed(seed, lat, lon);
    }

}
